//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErwMvcExtensions.ValidationAttributes.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationAttributeErrorMessageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationAttributeErrorMessageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ErwMvcExtensions.ValidationAttributes.Resources.ValidationAttributeErrorMessageRe" +
                            "sources", typeof(ValidationAttributeErrorMessageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} available only if  {1} {2} {3}..
        /// </summary>
        public static string AvailableIf {
            get {
                return ResourceManager.GetString("AvailableIf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be same as {1}..
        /// </summary>
        public static string EqualsToMultiple {
            get {
                return ResourceManager.GetString("EqualsToMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of uploaded files for the {0} should be in the range from {1} to {2}..
        /// </summary>
        public static string HttpPostedFileBaseCount {
            get {
                return ResourceManager.GetString("HttpPostedFileBaseCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid file extensions for the {0} is {1}..
        /// </summary>
        public static string HttpPostedFileBaseExtensions {
            get {
                return ResourceManager.GetString("HttpPostedFileBaseExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of the uploaded files for the {0} should be in the range from {1} to {2} {3}..
        /// </summary>
        public static string HttpPostedFileBaseSize {
            get {
                return ResourceManager.GetString("HttpPostedFileBaseSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be different from {1}..
        /// </summary>
        public static string NotEqualsTo {
            get {
                return ResourceManager.GetString("NotEqualsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This value is not valid for the {0}..
        /// </summary>
        public static string RemoteAndServer {
            get {
                return ResourceManager.GetString("RemoteAndServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required if {1} {2} {3}..
        /// </summary>
        public static string RequiredIf {
            get {
                return ResourceManager.GetString("RequiredIf", resourceCulture);
            }
        }
    }
}
